name: vgrade
favicon: null
layout_spectrum: 0.88824257790111
typography_spectrum: 0.826861249981448
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.43340237508527935
  lightness: 0.6644422002136707
  saturation: 0.2266705606598407
  rhythmicContrast: 0.113600263139233
purpose: []
