name: vgrade
favicon: null
layout_spectrum: 0.74051
typography_spectrum: 0.14014
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e3cba9'
    - '#5b5964'
    - '#aa6858'
    - '#bb9b75'
    - '#262431'
  brandStrength: 0.43340237508527935
  lightness: 0.6644422002136707
  saturation: 0.3125
  rhythmicContrast: 0.113600263139233
purpose: []
